name: Build Amandier Logic V1

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code (v4)
        uses: actions/checkout@v4

      - name: 2. Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 3. Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: 4. Get Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d_%Hh%M')" >> $GITHUB_OUTPUT

      - name: 5. Install Dependencies
        run: flutter pub get

      - name: 6. Build APK (Debug)
        run: flutter build apk --debug --no-tree-shake-icons

      - name: 7. Rename APK
        run: |
          mv build/app/outputs/flutter-apk/app-debug.apk build/app/outputs/flutter-apk/Amandier_DEBUG_${{ steps.date.outputs.date }}.apk

      - name: 8. Upload Artifact (v4 FIXED)
        uses: actions/upload-artifact@v4
        with:
          name: APK_Amandier_Debug_${{ steps.date.outputs.date }}
          path: build/app/outputs/flutter-apk/Amandier_DEBUG_${{ steps.date.outputs.date }}.apk
          retention-days: 5
